package eu.jgen.notes.tstuaf1.samples;

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
//
//                    Source Code Generated by
//                           CA Gen 8.6
//
//    Copyright (c) 2017 CA Technologies. All rights reserved.
//
//    Name: FAB01                            Date: 2017/09/10
//    Target OS:   JVM                       Time: 22:43:30
//    Target DBMS: JDBC                      User: Marek
//    Access Method: JDBC           
//
//    Generation options:
//    Debug trace option not selected
//    Data modeling constraint enforcement not selected
//    Optimized import view initialization not selected
//    Enforce default values with DBMS not selected
//    Init unspecified optional fields to NULL not selected
//
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
// Import Statements
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
import java.lang.*;
import java.io.*;
import java.util.*;
import java.math.*;
import java.sql.*;
import com.ca.gen.vwrt.*;
import com.ca.gen.vwrt.types.*;
import com.ca.gen.vwrt.vdf.*;

import com.ca.gen.abrt.*;
import com.ca.gen.abrt.functions.*;
import com.ca.gen.abrt.cascade.*;
import com.ca.gen.abrt.trace.*;
import com.ca.gen.exits.common.*;
import com.ca.gen.odc.*;

public class AB01 extends ABBase
{
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  // IMPORT VIEW CLASS VARIABLE
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  AB01_IA w_ia;
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  // EXPORT VIEW CLASS VARIABLE
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  AB01_OA w_oa;
  
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  // ACTION BLOCK IMPORT/EXPORT VIEWS CLASS VARIABLES
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  eu.jgen.notes.tstuaf1.samples.AB02_IA ab02_ia;
  eu.jgen.notes.tstuaf1.samples.AB02_OA ab02_oa;
  
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  // MISC DECLARATIONS AND PROTOTYPES 
  //    FOLLOW AS NEEDED:             
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  boolean func_0022020096_esc_flag;
  //       +->   FAB01                             09/10/2017  22:43
  //       !       IMPORTS:
  //       !         Work View imp1 ief_supplied (Transient, Optional,
  //       !                     Import only)
  //       !           count
  //       !         Work View imp2 ief_supplied (Transient, Mandatory,
  //       !                     Import only)
  //       !           count
  //       !       EXPORTS:
  //       !         Work View exp ief_supplied (Transient, Export only)
  //       !           count
  //       !
  //       !     PROCEDURE STATEMENTS
  //       !
  //     1 !  USE ab02
  //     1 !     WHICH IMPORTS: Work View imp2 ief_supplied TO Work View
  //     1 !              imp2 ief_supplied
  //     1 !                    Work View imp1 ief_supplied TO Work View
  //     1 !              imp1 ief_supplied
  //     1 !     WHICH EXPORTS: Work View exp ief_supplied FROM Work View
  //     1 !              exp ief_supplied
  //       +---
  
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  //  CONSTRUCTOR FOR THE CLASS       
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  public AB01()
  {
    iefCGenRlse = "CA Gen 8.6";
    ssCopyright = "Copyright (c) 2017 CA Technologies. All rights reserved.";
    iefCGenDate = "2017/09/10";
    iefCGenTime = "22:43:30";
    iefCGenEncy = "9.2.A6";
    iefCGenUserId = "Marek";
    iefCGenModel = "TSTUAF1";
    iefCGenSubset = "ALL";
    iefCGenName = "FAB01";
    nestingLevel = 0;
    valChkDeadlockTimeout = false;
    valChkDBError = false;
  }
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  // ACTION BLOCK FUNCTION DECLARATIONS 
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  
  public void AB01( Object in_runtime_parm1, 
  	IRuntimePStepContext in_runtime_parm2, 
  	GlobData in_globdata, 
  	AB01_IA import_view, 
  	AB01_OA export_view )
  {
    iefRuntimeParm1 = in_runtime_parm1;
    iefRuntimeParm2 = in_runtime_parm2;
    globdata = in_globdata;
    w_ia = import_view;
    w_oa = export_view;
    _AB01();
  }
  
  private void _AB01()
  {
    
    ++(nestingLevel);
    try {
      f_22020096_init();
      f_22020096();
    } catch( ABException e ) {
    } finally {
      --(nestingLevel);
    }
  }
  public void f_22020096()
  	throws ABException
  {
    func_0022020096_esc_flag = false;
    globdata.getStateData().setCurrentABId( "0022020096" );
    globdata.getStateData().setCurrentABName( "FAB01" );
    globdata.getStateData().setLastStatementNumber( "0000000001" );
    
    ab02_ia = (eu.jgen.notes.tstuaf1.samples.AB02_IA)(iefRuntimeParm2.getInstance("eu.jgen.notes.tstuaf1.samples.AB02_IA"));
    ab02_oa = (eu.jgen.notes.tstuaf1.samples.AB02_OA)(iefRuntimeParm2.getInstance("eu.jgen.notes.tstuaf1.samples.AB02_OA"));
    ab02_ia.Imp1IefSuppliedCount = IntAttr.valueOf(w_ia.Imp1IefSuppliedCount);
    ab02_ia.Imp2IefSuppliedCount = IntAttr.valueOf(w_ia.Imp2IefSuppliedCount);
    globdata.getErrorData().setErrorEncounteredSW( ErrorData.NO_ERROR_FOUND_SW );
    iefRuntimeParm2.useActionBlock("eu.jgen.notes.tstuaf1.samples.AB02", "AB02", ab02_ia, ab02_oa);
    if ( ((!(globdata.getErrorData().getStatus().equals( ErrorData.NONE_SF ))) || (globdata.getErrorData().getErrorEncounteredSW() 
      != ErrorData.NO_ERROR_FOUND_SW)) || (globdata.getErrorData().getViewOverflowSW() != ErrorData.NO_ERROR_FOUND_SW) )
    {
      throw new ABException();
    }
    globdata.getStateData().setCurrentABId( "0022020096" );
    globdata.getStateData().setCurrentABName( "FAB01" );
    globdata.getStateData().setLastStatementNumber( "0000000001" );
    w_oa.ExpIefSuppliedCount = IntAttr.valueOf(ab02_oa.ExpIefSuppliedCount);
    ab02_ia.freeInstance();
    ab02_ia = null;
    ab02_oa.freeInstance();
    ab02_oa = null;
  }
  
  
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  // SUBORDINATE FUNCTIONS
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  // INITIALIZATION UTILITY FUNCTIONS 
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  
  public void f_22020096_init()
  	throws ABException
  {
    if ( nestingLevel < 2 )
    {
    }
    w_oa.ExpIefSuppliedCount = 0;
  }
}// end class

