package eu.jgen.notes.tstuaf1.samples;
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
//
//                    Source Code Generated by
//                           CA Gen 8.6
//
//    Copyright (c) 2017 CA Technologies. All rights reserved.
//
//    Name: AB02_LA                          Date: 2017/09/10
//    User: Marek                            Time: 22:43:30
//
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
// Import Statements
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
import java.lang.*;
import java.io.*;
import java.util.*;
import java.math.*;
import java.sql.*;
import com.ca.gen.vwrt.*;
import com.ca.gen.vwrt.types.*;
import com.ca.gen.vwrt.vdf.*;
import com.ca.gen.csu.exception.*;

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
// START OF LOCAL VIEW
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
/**
 * Internal data view storage for: AB02_LA
 **/
public class AB02_LA extends ViewBase implements ILocalView, Serializable
{
  // Entity View: LOC
  //        Type: IEF_SUPPLIED
  /**
   * Attribute missing flag for: LocIefSuppliedCommand
   **/
  public char LocIefSuppliedCommand_AS;
  /**
   * Attribute for: LocIefSuppliedCommand
   * Domain: Text
   * Length: 80
   * Varying Length: N
   **/
  public String LocIefSuppliedCommand;
  /**
   * Default Constructor
   **/
  
  public AB02_LA()
  {
    reset();
  }
  /**
   * Copy Constructor
   **/
  
  public AB02_LA(AB02_LA orig)
  {
    LocIefSuppliedCommand_AS = orig.LocIefSuppliedCommand_AS;
    LocIefSuppliedCommand = orig.LocIefSuppliedCommand;
  }
  /**
   * Static instance creator function
   **/
  
  public static AB02_LA getInstance()
  {
    return new AB02_LA();
  }
  /**
   * Static free instance method
   **/
  
  public void freeInstance()
  {
  }
  /**
   * clone constructor
   **/
  
  @Override public Object clone()
  	throws CloneNotSupportedException
  {
    return(new AB02_LA(this));
  }
  /**
   * Resets all properties to the defaults.
   **/
  
  public void reset()
  {
    LocIefSuppliedCommand_AS = ' ';
    LocIefSuppliedCommand = "                                                                                ";
  }
}
