package eu.jgen.notes.tstuaf1.samples;

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
//
//                    Source Code Generated by
//                           CA Gen 8.6
//
//    Copyright (c) 2017 CA Technologies. All rights reserved.
//
//    Name: AB03                             Date: 2017/09/10
//    Target OS:   JVM                       Time: 22:43:30
//    Target DBMS: JDBC                      User: Marek
//    Access Method: JDBC           
//
//    Generation options:
//    Debug trace option not selected
//    Data modeling constraint enforcement not selected
//    Optimized import view initialization not selected
//    Enforce default values with DBMS not selected
//    Init unspecified optional fields to NULL not selected
//
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
// Import Statements
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
import java.lang.*;
import java.io.*;
import java.util.*;
import java.math.*;
import java.sql.*;
import com.ca.gen.vwrt.*;
import com.ca.gen.vwrt.types.*;
import com.ca.gen.vwrt.vdf.*;

import com.ca.gen.abrt.*;
import com.ca.gen.abrt.functions.*;
import com.ca.gen.abrt.cascade.*;
import com.ca.gen.abrt.trace.*;
import com.ca.gen.exits.common.*;
import com.ca.gen.odc.*;

public class AB03 extends ABBase
{
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  // IMPORT VIEW CLASS VARIABLE
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  AB03_IA w_ia;
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  // EXPORT VIEW CLASS VARIABLE
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  AB03_OA w_oa;
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  // LOCAL VIEW CLASS VARIABLE
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  AB03_LA w_la;
  
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  // MISC DECLARATIONS AND PROTOTYPES 
  //    FOLLOW AS NEEDED:             
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  boolean func_0022020098_esc_flag;
  //       +->   AB03                              09/10/2017  22:43
  //       !       IMPORTS:
  //       !         Work View imp1 ief_supplied (Transient, Optional,
  //       !                     Import only)
  //       !           count
  //       !         Work View imp2 ief_supplied (Transient, Mandatory,
  //       !                     Import only)
  //       !           count
  //       !       EXPORTS:
  //       !         Work View exp ief_supplied (Transient, Export only)
  //       !           count
  //       !       LOCALS:
  //       !         Work View loc ief_supplied
  //       !           command
  //       !
  //       !     PROCEDURE STATEMENTS
  //       !
  //     1 !  SET exp ief_supplied count TO imp1 ief_supplied count + imp2
  //     1 !              ief_supplied count 
  //       +---
  
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  //  CONSTRUCTOR FOR THE CLASS       
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  public AB03()
  {
    iefCGenRlse = "CA Gen 8.6";
    ssCopyright = "Copyright (c) 2017 CA Technologies. All rights reserved.";
    iefCGenDate = "2017/09/10";
    iefCGenTime = "22:43:30";
    iefCGenEncy = "9.2.A6";
    iefCGenUserId = "Marek";
    iefCGenModel = "TSTUAF1";
    iefCGenSubset = "ALL";
    iefCGenName = "AB03";
    nestingLevel = 0;
    valChkDeadlockTimeout = false;
    valChkDBError = false;
  }
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  // ACTION BLOCK FUNCTION DECLARATIONS 
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  
  public void AB03( Object in_runtime_parm1, 
  	IRuntimePStepContext in_runtime_parm2, 
  	GlobData in_globdata, 
  	AB03_IA import_view, 
  	AB03_OA export_view )
  {
    iefRuntimeParm1 = in_runtime_parm1;
    iefRuntimeParm2 = in_runtime_parm2;
    globdata = in_globdata;
    w_ia = import_view;
    w_oa = export_view;
    _AB03();
  }
  
  private void _AB03()
  {
    
    f_22020098_localAlloc("AB03");
    if ( globdata.getErrorData().getLastStatus() == ErrorData.IEF_ALLOCATION_ERROR_FL_LS )
    	return;
    
    ++(nestingLevel);
    try {
      f_22020098_init();
      f_22020098();
    } catch( ABException e ) {
    } finally {
      --(nestingLevel);
    }
  }
  public void f_22020098()
  	throws ABException
  {
    func_0022020098_esc_flag = false;
    globdata.getStateData().setCurrentABId( "0022020098" );
    globdata.getStateData().setCurrentABName( "AB03" );
    globdata.getStateData().setLastStatementNumber( "0000000001" );
    w_oa.ExpIefSuppliedCount = IntAttr.valueOf((int)TIRD2DEC.TIRD2DC1(((double) w_ia.Imp1IefSuppliedCount + (double) 
      w_ia.Imp2IefSuppliedCount), 0, TIRD2DEC.ROUND_NONE, 9));
  }
  
  
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  // SUBORDINATE FUNCTIONS
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  // INITIALIZATION UTILITY FUNCTIONS 
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  
  public void f_22020098_localAlloc(String abname)
  {
    // Request localview allocation 
    w_la = (eu.jgen.notes.tstuaf1.samples.AB03_LA)(iefRuntimeParm2.getInstance("eu.jgen.notes.tstuaf1.samples.AB03_LA"));
    if ( w_la == null )
    {
      globdata.getStateData().setCurrentABId( "0022020098" );
      globdata.getStateData().setCurrentABName( abname );
      globdata.getErrorData().setErrorEncounteredSW( ErrorData.ERROR_FOUND_SW );
      globdata.getErrorData().setLastStatus( ErrorData.IEF_ALLOCATION_ERROR_FL_LS );
    }
  }
  
  public void f_22020098_init()
  	throws ABException
  {
    if ( nestingLevel < 2 )
    {
      w_la.reset();
    }
    w_oa.ExpIefSuppliedCount = 0;
  }
}// end class

