package eu.jgen.notes.tstuaf1.samples;
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
//
//                    Source Code Generated by
//                           CA Gen 8.6
//
//    Copyright (c) 2017 CA Technologies. All rights reserved.
//
//    Name: AB03_IA                          Date: 2017/09/10
//    User: Marek                            Time: 22:43:30
//
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
// Import Statements
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
import java.lang.*;
import java.io.*;
import java.util.*;
import java.math.*;
import java.sql.*;
import com.ca.gen.vwrt.*;
import com.ca.gen.vwrt.types.*;
import com.ca.gen.vwrt.vdf.*;
import com.ca.gen.csu.exception.*;

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
// START OF IMPORT VIEW
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
/**
 * Internal data view storage for: AB03_IA
 **/
public class AB03_IA extends ViewBase implements IImportView, Serializable
{
  // Entity View: IMP1
  //        Type: IEF_SUPPLIED
  /**
   * Attribute missing flag for: Imp1IefSuppliedCount
   **/
  public char Imp1IefSuppliedCount_AS;
  /**
   * Attribute for: Imp1IefSuppliedCount
   * Domain: Number
   * Length: 9
   * Decimal Places: 0
   * Decimal Precision: N
   **/
  public int Imp1IefSuppliedCount;
  // Entity View: IMP2
  //        Type: IEF_SUPPLIED
  /**
   * Attribute missing flag for: Imp2IefSuppliedCount
   **/
  public char Imp2IefSuppliedCount_AS;
  /**
   * Attribute for: Imp2IefSuppliedCount
   * Domain: Number
   * Length: 9
   * Decimal Places: 0
   * Decimal Precision: N
   **/
  public int Imp2IefSuppliedCount;
  /**
   * Default Constructor
   **/
  
  public AB03_IA()
  {
    reset();
  }
  /**
   * Copy Constructor
   **/
  
  public AB03_IA(AB03_IA orig)
  {
    copyFrom(orig);
  }
  /**
   * Static instance creator function
   **/
  
  public static AB03_IA getInstance()
  {
    return new AB03_IA();
  }
  /**
   * Static free instance method
   **/
  
  public void freeInstance()
  {
  }
  /**
   * clone constructor
   **/
  
  @Override public Object clone()
  	throws CloneNotSupportedException
  {
    return(new AB03_IA(this));
  }
  /**
   * Resets all properties to the defaults.
   **/
  
  public void reset()
  {
    Imp1IefSuppliedCount_AS = ' ';
    Imp1IefSuppliedCount = 0;
    Imp2IefSuppliedCount_AS = ' ';
    Imp2IefSuppliedCount = 0;
  }
  /**
   * Gets the VDF version of the current state of the instance.
   **/
  public VDF getVDF()
  {
    throw new RuntimeException("can only execute getVDF for a Procedure Step.");
  }
  
  /**
   * Sets the current state of the instance to the VDF version.
   **/
  public void setFromVDF(VDF vdf)
  {
    throw new RuntimeException("can only execute setFromVDF for a Procedure Step.");
  }
  
  /**
   * Sets the current instance based on the passed view.
   **/
  public void copyFrom(IImportView orig)
  {
    this.copyFrom((AB03_IA) orig);
  }
  
  /**
   * Sets the current instance based on the passed view.
   **/
  public void copyFrom(AB03_IA orig)
  {
    Imp1IefSuppliedCount_AS = orig.Imp1IefSuppliedCount_AS;
    Imp1IefSuppliedCount = orig.Imp1IefSuppliedCount;
    Imp2IefSuppliedCount_AS = orig.Imp2IefSuppliedCount_AS;
    Imp2IefSuppliedCount = orig.Imp2IefSuppliedCount;
  }
}
